blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('news/', views.news, name='news'),
    path('search/', views.search_function, name='search_url' ),
    path('news/<slug:slug>/', views.post_detail, name='post_detail_url'),
    path('news/<slug:slug>/comment/', views.comment, name='comment'),
    path('categories/<slug:slug>/', views.category_detail, name='category_detail_url'),
    path('register/', views.register, name='register'),
    path('sort/', views.sort, name="sort")
]

news_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse
from django.contrib.auth.models import User

class Category(models.Model):
	title = models.CharField('title', max_length = 255)
	slug = models.SlugField('link', unique = True)
	image = models.ImageField('image', blank = True, null = True)

	# Class Meta for russian language)
	class Meta:
		verbose_name = 'Category'
		verbose_name_plural = 'Categories'

	def get_absolute_url(self):
		return reverse('category_detail_url', kwargs={'slug': self.slug})

	def __str__(self):
		return self.title

class Post(models.Model):
	title = models.CharField('title', max_length = 255)
	slug = models.SlugField('link', unique = True)
	image = models.ImageField('image', blank = True, null = True)
	category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, verbose_name = 'Category')
	content = models.TextField('text')
	date = models.DateTimeField('Date', default = timezone.now)
	publish = models.BooleanField('Publicated', default = True)
	views = models.IntegerField('Views', default=0)

	# Class Meta for russian language)
	class Meta:
		verbose_name = 'news'
		verbose_name_plural = 'news'

	def get_absolute_url(self):
		return reverse('post_detail_url', kwargs={'slug': self.slug})

	def __str__(self):
		return self.title

class Comment(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Author')
	post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='News')
	text = models.TextField('Comment')
	date = models.DateTimeField('Date', default=timezone.now)

	class Meta:
		verbose_name = 'comment'
		verbose_name_plural = 'comments'

	def __str__(self):
		return self.user.username

blog/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
	username = forms.CharField(label='nickname', required=True, widget=forms.TextInput(attrs={'class': 'form-control mb-20'}))
	password1 = forms.CharField(label='password1', required=True, widget=forms.PasswordInput(attrs={'class': 'form-control mb-20'}))
	password2 = forms.CharField(label='password(again)', required=True, widget=forms.PasswordInput(attrs={'class': 'form-control mb-20'}))
	email = forms.EmailField(label='email', required=True, widget=forms.TextInput(attrs={'class': 'form-control mb-20'}))
	first_name = forms.CharField(label='name', required=True, widget=forms.TextInput(attrs={'class': 'form-control mb-20'}))
	last_name = forms.CharField(label='surname', required=True, widget=forms.TextInput(attrs={'class': 'form-control mb-20'}))

	class Meta():
		model = User
		fields = ('username','email','password1','password2','first_name','last_name',)

	def save(self, commit=True):
		user = super().save(commit=False)
		user.email = self.cleaned_data['email']
		user.first_name = self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']
		if commit:
			user.save()
			return user

blog/views.py
from django.shortcuts import render, redirect, reverse
from .models import Post, Category
from django.db.models import Q
from .forms import RegisterForm

def index(request):
	posts = Post.objects.filter(publish = 1).order_by('-views')[:9]
	sliders = Post.objects.filter(publish = 1).filter(views__gte=10).order_by('-views')[:10]
	categories = Category.objects.order_by('models.py')[:12]
	context = {'news': posts, 'sliders': sliders, 'categories': categories}
	return render(request, 'blog/index.html', context)

def news(request):
    posts = Post.objects.all()
    return render(request, 'blog/news.html', {'posts': posts})

def search_function(request):
	query = request.GET.get('search_input')
	posts = Post.objects.filter(Q(title__icontains = query))
	return render(request, 'blog/search.html', {'query': query, 'posts': posts})

def post_detail(request, slug):
	post = Post.objects.get(slug__exact = slug)
	post.views += 1
	post.save()
	return render(request, 'blog/post_detail.html', {'post': post})

def category_detail(request, slug):
	category = Category.objects.get(slug__exact = slug)
	return render(request, 'blog/category_detail.html', {'category': category})

def register(request):
	if not request.user.is_authenticated:
		if request.method == 'POST':
			form = RegisterForm(request.POST)
			if form.is_valid():
				form.save()
				return redirect('login')
		else:
			form = RegisterForm()
		return render(request, 'blog/register.html', {'form': form})
	return redirect('index')

def comment(request, slug):
	post = Post.objects.get(slug__exact=slug)
	if request.method == 'POST':
		post.comment_set.create(
			user = request.user,
			text = request.POST.get('text'),
		)
		return redirect(reverse('post_detail_url', kwargs={'slug': post.slug}))
	return redirect(reverse('post_detail_url', {'slug': post.slug}))

def sort(request):
	query = request.GET.get('sort')
	posts = Post.objects.order_by(query)
	return render(request, 'blog/sort.html', {'posts': posts, 'query': query})

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>News</title>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="base.css">
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	  <a class="navbar-brand" href="#">
	  	<img style="width: 80px; height: 80px;" src="https://cdn3.iconfinder.com/data/icons/ballicons-reloaded-free/512/icon-70-512.png" alt="">
	  </a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
	        <a class="nav-link" href="{% url 'news' %}">NEWS</a>
	      </li>
	      <li class="nav-item active">
	        <a class="nav-link" href="https://screenrant.com/movie-reviews/" tabindex="-1" aria-disabled="true">REVIEWS</a>
	      </li>
	      <li class="nav-item active">
	        <a class="nav-link" href="https://screenrant.com/movie-news/">MOVIE NEWS</a>
	      </li>
	      <li class="nav-item active">
	        <a class="nav-link" href="https://screenrant.com/interviews/" tabindex="-1" aria-disabled="true">INTERVIEWS</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'index' %}">MAIN</a>
	      </li>
	      {% if not user.is_authenticated %}
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'register' %}">Registration</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'login' %}">Login</a>
	      </li>
	      {% else %}
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
	      </li>
	      {% endif %}
	    </ul>
	    <form action="{% url 'search_url' %}" method="GET" class="form-inline my-2 my-lg-0">
	      <input name="search_input" style="border-radius: 10px" class="form-control mr-sm-2" type="search" placeholder="Search..." aria-label="Search">
	      <button style="border: none; border-radius: 50px" class="btn btn-outline-success my-2 my-sm-0" type="submit">
	      		<img style="width: 30px; height: 30px" src="https://i.pinimg.com/originals/e7/d4/50/e7d450d8c31ae10aa663d082fdbb3db9.png" alt="">
	      </button>
	    </form>
	  </div>
	</nav>

    {% block content %}



    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="{% static 'bootstrap.min.js' %}"></script>

</body>
</html>

blog/templates/blog/category_detail.html
{% extends 'base.html' %}

{% block title %}
{{category.title}}

{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-9">
			{% if category.image.url != null %}
			<img src="" alt="" style="width: 100%; height: 300px; object-fit: cover;">
			{% endif %}
			<h3>{{category.title}} category</h3>
			<hr style="border: 3px solid gray; border-radius: 10px;">
			<div class="row">
				{% for post in category.post_set.all %}
				<div class="card" style="width: 22rem; border: none; margin-top: 20px;">
				{% if post.image.url != null %}
				  <img style="height: 240px;" src="{{post.image.url}}" class="card-img-top" alt="...">
				{% endif %}
				  <div class="card-body">
				    <p class="card-text">{{post.content|safe}}...</p>
				    <a href="{{post.category.get_absolute_url}}" class="btn btn-primary">{{post.category.title}}</a>
				  </div>
				</div>
				{% endfor %}
			</div>
		</div>
		<div class="col-md-3"></div>
	</div>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block content %}
	
	<section class="container">
		<div class="row">
			
			<div class="col-md-8" style="margin-top: 20px;">

				<h4><i>LATEST</i></h4>
				<hr style="border: 3px solid gray; border-radius: 10px;">
				
				<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel" style="margin-top: 20px">
				  <ol class="carousel-indicators">
				    {% for post in sliders %}
				    <li data-target="#carouselExampleCaptions" data-slide-to="{{forloop.counter0}}" {% if forloop.first %} class="active" {% endif %}></li>
				  	{% endfor %}
				  </ol>
				  <div class="carousel-inner">
				  	{% for post in sliders %}
				    <div class="carousel-item {% if forloop.first %} active {% endif %}">
				    	{% if post.image.url != null %}
				      <img style="height: 370px; object-fit: cover;" src="{{post.image.url}}" class="d-block w-100" alt="...">
				      	{% endif %}
				      <div class="carousel-caption d-none d-md-block">
				        <a href="{{post.get_absolute_url}}">
				        	<h5>{{post.title}}</h5>
				        </a>
				        <a>{{post.content|safe|slice:"0:100"}}...</a>
				      </div>
				    </div>
				    {% endfor %}
				  </div>
				  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
				    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
				    <span class="sr-only">Previous</span>
				  </a>
				  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
				    <span class="carousel-control-next-icon" aria-hidden="true"></span>
				    <span class="sr-only">Next</span>
				  </a>
				</div>

				<img style="margin-top: 20px; height: 350px; width: 100%; object-fit: cover;" src="https://upload.wikimedia.org/wikipedia/commons/5/53/Sololearn_logo.jpg" class="img-fluid" alt="Responsive image">
					<h2 style="text-align: center;">SoloLearn</h2>
					<p style="text-align: center;">Learn Playing. Play learning</p>
				<img style="margin-top: 20px; height: 350px; width: 100%; object-fit: cover; height: 285px; width: 100%; object-fit: cover;" src="https://freelancehunt.com/static/images/freelancehunt-header-en.png" class="img-fluid" alt="Responsive image">
					<h2 style="text-align: center;">freelancehunt</h2>
					<p style="text-align: center;">Simple and reliable freelance</p>
				<img style="margin-top: 20px; height: 350px; width: 100%; object-fit: cover;" src="https://miro.medium.com/max/10000/1*HLGtY6O2vUHqIyEbWdmBgA.jpeg" class="img-fluid" alt="Responsive image">
				<img style="margin-top: 20px; height: 250px; width: 100%; object-fit: cover;" src="https://maxime-garnier.fr/assets/images/uploads/426acf8575332de8506883cbb1289e65.jpg" class="img-fluid" alt="Responsive image">
				<img style="margin-top: 20px; height: 400px; width: 100%; object-fit: cover;" src="https://miro.medium.com/max/12032/0*DypQzAMdE9cudggX" class="img-fluid" alt="Responsive image">
				<img style="margin-top: 20px; height: 300px; width: 100%; object-fit: cover;" src="https://miro.medium.com/max/1470/1*4IWsNF0FGF9zhMuipgN5Tw.jpeg" class="img-fluid" alt="Responsive image">
				<img style="margin-top: 20px; height: 400px; width: 100%; object-fit: cover;" src="https://static.macupdate.com/screenshots/251570/m/xcode-screenshot.png?v=1594884596" class="img-fluid" alt="Responsive image">
				<img style="margin-top: 20px; height: 380px; width: 100%; object-fit: cover;" src="https://www.apple.com/newsroom/images/product/os/macos/standard/apple_macos-bigsur_redesignedapps_06222020_big.jpg.large.jpg" class="img-fluid" alt="Responsive image">
		
			</div>

			<div class="col-md-4" style="margin-top: 20px">
				
				<h4><i>TRENDING</i></h4>
				<hr style="border: 3px solid gray; border-radius: 10px;">
				{% for post in news %}
				<div class="card" style="width: 22rem; border: none; margin-top: 20px;">
				{% if post.image.url != null %}
				  <img style="height: 240px;" src="{{post.image.url}}" class="card-img-top" alt="...">
				{% endif %}
				  <div class="card-body">
				  	<a href="{{post.get_absolute_url}}">
				        <h5>{{post.title}}</h5>
				    </a>
				    <p class="card-text">{{post.content|safe|slice:"0:100"}}...</p>
				    <b>Views: {{post.views}}</b>
				    <a href="{{post.category.get_absolute_url}}" class="btn btn-primary">{{post.category.title}}</a>
				  </div>
				</div>
				{% endfor %}
			</div>
		</div>
	</section>
	<section>
        <footer id="footer">
            <h6 style="text-align: center; margin: 50px 0 10px 0; color: rgba(0, 0, 0, .7);">COPYRIGHT &copy; DEVELOPER / ABDULAZIZ. ALL RIGHTS RESERVED</h6>
        </footer>
    </section>

{% endblock %}

blog/templates/blog/news.html
{% extends 'base.html' %}

{% block title %}
Search for query: {{query}}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <div class="row">
                {% for post in posts %}
                    <div class="col-md-4">
                        {% if post.image.url != null %}
                        <img src="{{post.image.url}}" style="height: 200px; width: 100%; object-fit: cover" alt="">
                        {% endif %}
                        <a href="{{post.get_absolute_url}}">
                            <h5>{{post.title}}</h5>
                        </a>
                    </div>
                {% empty %}
                <h2>По запросу "{{query}}" ничего не найдено!</h2>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-3">
            <form action="{% url 'sort' %}" method="GET">
            <select name="sort" onchange="{this.form.submit()}">
                <option value="-date">Latest</option>
                <option value="date">Old</option>
                <option value="-views">Featured</option>
                <option value="views">Shit</option>
            </select>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}
{{post.title}}

{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-9">
			{% if post.image.url != null %}
			<img src="" alt="">
			{% endif %}
			<h3>{{post.title}}</h3>
			<p>{{post.content|safe}}</p>
			<p class="text-right">
				<b>Views: {{post.views}}</b> |
				<i>{{post.date|date:"d F, Y"}}</i>
			</p>
			<p>
				<i>
					Comments about: {{post.comment_set.count}}
				</i>
			</p>
			<hr>
			<h3>Leave a comment</h3>
			{% if user.is_authenticated %}
			<form action="{% url 'comment' post.slug %}" method="POST">
				{% csrf_token %}
				<p>
					<textarea name="text" class="form-control">
						
					</textarea>
				</p>
				<p class="text-right">
					<button class="btn btn-outline-primary">
						Send
					</button>
				</p>
			</form>
			{% else %}
			<p>
				to leave a comment,
				<a href="{% url 'register' %}">
					sign up
				</a>
				or
				<a href="{% url 'login' %}">
					login
				</a>
			</p>
			{% endif %}
			<hr>
			{% for comment in post.comment_set.all %}
			<div class="col-md-12">
				<h3>{{comment.user.username}}</h3>
				<p>
					{{comment.text}}
				</p>
				<p class="text-right">
					{{comment.date|timesince}} ago
				</p>
			</div>
			{% endfor %}
		</div>
		<div class="col-md-3">
			


		</div>
	</div>
</div>
{% endblock %}

blog/templates/blog/register.html
{% extends 'base.html' %}

{% block title %}
Registration
{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-9">
			<form action="{% url 'register' %}" method="POST">
				{% csrf_token %}
				{{form.as_p}}
				<button class="btn btn-success">Registration</button>
			</form>
		</div>
		<div class="col-md-3">
			
		</div>
	</div>
</div>
{% endblock %}

blog/templates/blog/search.html
{% extends 'base.html' %}

{% block title %}

	Search for: {{query}}

{% endblock %}

{% block content %}

	<div class="container">
		<div class="row">
			<div class="col-md-9">
				<div class="row">
					{% for post in posts %}
						<div class="col-md-4">
							{% if post.image.url != null %}
							<img src="{{post.image.url}}" style="height: 300px; width: 230px; object-fit: cover;" alt="">
							{% endif %}
							<a href="{{post.category.get_absolute_url}}" title="">
								<h3 class="text-center">{{post.title}}</h3>
							</a>
							<p style="text-align: center;">{{post.content|safe|slice:"0:140"}}...</p>
						</div>
					{% empty %}
					<h2>Didn't find for search: "{{query}}"</h2>
					{% endfor %}
				</div>
			</div>
			<div class="col-md-3">
				
			</div>
		</div>
	</div>

{% endblock %}

blog/templates/blog/sort.html
{% extends 'base.html' %}

{% block title %}
Search for query: {{query}}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <div class="row">
                {% for post in posts %}
                    <div class="col-md-4">
                        {% if post.image.url != null %}
                        <img src="{{post.image.url}}" style="height: 200px; width: 100%; object-fit: cover" alt="">
                        {% endif %}
                        <h3 class="text-center">{{post.title}}</h3>
                    </div>
                {% empty %}
                <h2>По запросу "{{query}}" ничего не найдено!</h2>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-3">
            <form action="{% url 'sort' %}" method="GET">
            <select name="sort" onchange="{this.form.submit()}">
                <option {% if query == '-date' %} selected {% endif %} value="-date">Latest</option>
                <option {% if query == 'date' %} selected {% endif %} value="date">Old</option>
                <option {% if query == '-views' %} selected {% endif %} value="-views">Featured</option>
                <option {% if query == 'views' %} selected {% endif %} value="views">Shit</option>
            </select>
            </form>
        </div>
    </div>
</div>
{% endblock %}